### ISSUE TITLE
html to pdf why not working am following Our Offcial Git repo page

### ISSUE THREAD

**Issue by MuthukumarHelios** [janczer/htmlPDF#2]
```go
package main 
import    "github.com/janczer/htmlPDF"
func main(){
html := `<h1 class="a">hello</h1>`
	css  :=  `.a { background: #ff0000; }`
//What is the issue here 
	htmlPDF.Generate(html, css, "hello12345.pdf")
	
}
```

---
I dont Know What i am doing wrong 

>go version 
`go version go1.9.2 linux/amd64`

**Comment by janczer** [comment]
If you use function `Generate` you should provide name of files: html, css and pdf.

For example, if you create in the same directory 3 files: `first.html`, `style.css` and `main.go`:

first.html:
```
<h1 class="a">hello</h1>
```

style.css:
```
* { display: block; padding: 5px; }
.a { background: #ff0000; }
```

main.go
```
package main 
import    "github.com/janczer/htmlPDF"
func main() {
    htmlPDF.Generate("first.html", "style.css", "hello.pdf")
}
```

Now you can run go program:

```
$ go run main.go
```

Program should create file `hello.pdf`.

-----

In the last commit bc5f4ad88c42fa76239b5f8acac7c088fd353bbd I added function `GenerateFromString` so now you can use string variable:

```
package main 
import    "github.com/janczer/htmlPDF"
func main() {
	html := `<h1 class="a">hello</h1>`
	css  :=  `.a { background: #ff0000; } * { display: block; padding: 5px; }`
	htmlPDF.GenerateFromString(html, css, "hello12345.pdf")
}
```

**Comment by MuthukumarHelios** [comment]
@janczer Thank you for your Reponse 


Case 1 ==> 	``htmlPDF.Generate("hello.html", "hello.css", "hello12345.pdf")``
>It throws me the below Error
```
print Node
html text: 
    head text: 
    body text: 
        h1 text: 
             text: hello to pdf
end print Node

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/janczer/htmlPDF.(*Parser).consumeChar(...)
	/home/user/go/src/github.com/janczer/htmlPDF/html.go:186
github.com/janczer/htmlPDF.(*Parser).parseDeclaration(0xc420055da0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/go/src/github.com/janczer/htmlPDF/css.go:137 +0x24f
github.com/janczer/htmlPDF.(*Parser).parseDeclarations(0xc420055da0, 0xc4201e4300)
	/home/user/go/src/github.com/janczer/htmlPDF/css.go:122 +0x126
github.com/janczer/htmlPDF.(*Parser).parseRule(0xc420055da0, 0x0)
	/home/user/go/src/github.com/janczer/htmlPDF/css.go:108 +0x47
github.com/janczer/htmlPDF.(*Parser).parseRules(0xc420055da0, 0xc4201f8000)
	/home/user/go/src/github.com/janczer/htmlPDF/css.go:97 +0x94
github.com/janczer/htmlPDF.Generate(0x7553dd, 0xa, 0x754de5, 0x9, 0x756815, 0xe)
	/home/user/go/src/github.com/janczer/htmlPDF/main.go:30 +0x214
main.main()
	/home/user/projects/smart/feedback_app/src/test_app/main.go:31 +0x75
exit status 2
```
--In our Source Code 

[html.go](https://github.com/janczer/htmlPDF/blob/master/html.go#L186)
[css.go](https://github.com/janczer/htmlPDF/blob/master/css.go#L137)
[css.go](https://github.com/janczer/htmlPDF/blob/master/css.go#L122)
[css.go])(https://github.com/janczer/htmlPDF/blob/master/css.go#L97)
[main.go](https://github.com/janczer/htmlPDF/blob/master/main.go#L30)

>Case 2 

```
func main(){
html := `<h1 class="a">hello</h1>`
	css  :=  `.a { background: #ff0000; }`
 htmlPDF.GenerateFromString(html, css, "hello12345.pdf")
}
```
*error*
```

print Node
h1 text: 
     text: hello
end print Node

print StyleTree
node &{map[0:0xc42006d260] {{h1 map[class:a]} }}
specified_values len 1
childrens: 
    node &{map[] {{ map[]} hello}}
    specified_values len 0
    childrens: 
end print StyleTree

inline
{}
last container htmlPDF.InlineNode{}
inline
{}
layout inlinenode
{x:0 y:0 width:210 height:0}layout inlinenode
{x:0 y:0 width:0 height:0}
print LayoutTree
dimensions {content:{x:0 y:0 width:0 height:0} padding:{left:0 right:0 top:0 bottom:0} border:{left:0 right:0 top:0 bottom:0} margin:{left:0 right:0 top:0 bottom:0}}
box type htmlPDF.InlineNode{}
    dimensions {content:{x:0 y:0 width:0 height:0} padding:{left:0 right:0 top:0 bottom:0} border:{left:0 right:0 top:0 bottom:0} margin:{left:0 right:0 top:0 bottom:0}}
    box type htmlPDF.InlineNode{}
end print LayoutTree
hello
&{{{0 0 0 0} {0 0 0 0} {0 0 0 0} {0 0 0 0}} {} map[0:0xc420098370] {0xc42006d470 map[background:{ {0 } {255 0 0 255}}] map[0:{0xc42006d260 map[] map[]}]}}
your app running on :8081
```
**But my App is still running**

I don't Know why it's Throwing Error 
 [.GenerateFromString func](https://github.com/janczer/htmlPDF/blob/master/main.go#L61)

In think Both case 1 and case 2 are failling because they are unable to parse the html
